{{- $fullName := include "pm-cb-redis.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "pm-cb-redis.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ include "pm-cb-redis.password" . | b64enc | quote }}