{{- $fullName := include "redis.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ include "redis.password" . | b64enc | quote }}
