{{- $fullName := include "redis.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-master
  labels:
    {{- include "redis.labels" . | nindent 4 }}
    role: master
spec:
  ports:
  - port: 6379
    targetPort: redis
    name: redis
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
    role: master
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-replica
  labels:
    {{- include "redis.labels" . | nindent 4 }}
    role: replica
spec:
  ports:
  - port: 6379
    targetPort: redis
    name: redis
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
    role: replica
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-headless
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: redis
    name: redis
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
